[project]
name = "resume-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.99.1",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
]
